aqora-io/cli

Cargo.lock, Cargo.toml, config/src/lib.rs, runner/Cargo.toml, runner/src/python.rs, src/commands/install.rs, src/commands/python.rs, src/commands/shell.rs, src/commands/test.rs, src/commands/upload.rs, src/dirs.rs, src/error.rs, src/graphql/get_competition_use_case.graphql, src/graphql/schema.graphql, src/process.rs, src/python.rs
- use uv instead of pip
- make competition overrideable by command line
=> replace pip with uv

.github/workflows/build.yaml, .github/workflows/cd.yaml, .github/workflows/ci.yaml, .gitignore, pyproject.toml
- add workflows
- better artifact management
=> package cli

runner/src/python.rs, src/commands/clean.rs, src/commands/upload.rs, src/dirs.rs, src/python.rs
- **fix: better debug messages for pip install**
- **fix: use windows naming for virtual environment subdirectories**
- **fix: remove symlink dir reference in clean**
- **fix: allow for windows style virtual environment site-packages**
- **initialize virtual environment before upload**
=> fix install and upload for windows

Cargo.lock, Cargo.toml, config/Cargo.toml, config/src/lib.rs, pyproject.toml, src/colors.rs, src/commands/test.rs, src/commands/upload.rs, src/dirs.rs, src/graphql/competition_by_slug.graphql, src/graphql/competition_id_by_slug.graphql, src/graphql/latest_submission_version.graphql, src/python.rs
* ask to rerun tests if necessary
* automatically update use_case/submission version on upload
=> Ask to rerun tests on upload

pyproject.toml, src/commands/upload.rs, src/graphql/latest_submission_version.graphql, src/graphql/schema.graphql
Pull request on platform must be deployed first https://github.com/aqora-io/platform/pull/208
=> feat: tell the user where to accept competition rules

src/credentials.rs
i'm still not totally sure what the problem was, but this seems to work
better
=> fix: add sync_all to file replacement for credentials

src/revert_file.rs
and try to set the filetimes via File::set_times
=> fix: use copy instead of rename

Cargo.lock, config/Cargo.toml, config/src/lib.rs, runner/src/python.rs, src/commands/add.rs, src/commands/mod.rs, src/commands/remove.rs, src/error.rs, src/python.rs, src/revert_file.rs
- **feat: aqora add command**
- **feat: aqora remove command**
=> add and remove commands

Cargo.lock, Cargo.toml, build.rs, src/commands/clean.rs, src/commands/global_args.rs, src/commands/info.rs, src/commands/login.rs, src/commands/mod.rs, src/commands/version.rs, src/error.rs, src/lib.rs, src/main.rs, src/module.rs, src/revert_file.rs, src/sentry.rs
- **feat: sentry integration**
- **Add logging**
- **Colored terminal 😍**
=> feat sentry integration

Cargo.lock, Cargo.toml, config/src/lib.rs, runner/src/pipeline.rs, runner/src/python.rs, src/commands/clean.rs, src/commands/test.rs, src/commands/upload.rs, src/ipynb.rs, src/lib.rs, src/print.rs
- **add basic conversion for ipynb**
- **separate each cell into execs**
- **feat: use case notebook conversion and better print statements**
=> notebook submission

.github/workflows/cd.yaml, src/colors.rs, src/commands/add.rs, src/commands/clean.rs, src/commands/global_args.rs, src/commands/info.rs, src/commands/install.rs, src/commands/login.rs, src/commands/mod.rs, src/commands/python.rs, src/commands/remove.rs, src/commands/shell.rs, src/commands/template.rs, src/commands/test.rs, src/commands/upload.rs, src/sentry.rs
- **feat: better sentry context and event filtering**
- **fix: remove unnescessary warning flags**
- **fix: add sentry DSN to github workflow**
=> sentry workflow

Cargo.lock, Cargo.toml, pyproject.toml, runner/src/ipython.rs, runner/src/lib.rs, runner/src/python.rs, src/commands/clean.rs, src/commands/test.rs, src/commands/upload.rs, src/ipynb.rs, src/print.rs
- **feat: basic ipynb conversion using jupyter nbconvert**
- **fix: allow top level async statements in python notebooks**
- **feat: override ipython in runner**
=> fix notebook magic

runner/src/pipeline.rs, src/commands/mod.rs, src/commands/test.rs, src/lib.rs, src/main.rs, src/module.rs, src/run.rs
=> fix: sigsegv on low resource machines

Cargo.lock, Cargo.toml, runner/Cargo.toml, runner/src/python.rs, src/commands/info.rs, src/commands/test.rs, src/dirs.rs, src/ipynb.rs
- **feat: Add virtual environment info to aqora info**
- **fix: Use dunce to canonicalize paths**
=> fix: Jupyter templates not found on windows

Cargo.lock, Cargo.toml, runner/Cargo.toml, runner/src/python.rs, src/colors.rs, src/commands/add.rs, src/commands/global_args.rs, src/commands/info.rs, src/commands/install.rs, src/commands/lab.rs, src/commands/python.rs, src/commands/remove.rs, src/commands/shell.rs, src/commands/test.rs, src/commands/upload.rs, src/dirs.rs, src/ipynb.rs
- **refactor: Use options struct and short hand for env init**
- **feat: Add link mode to PyEnvOptions and PipOptions**
- **feat: Add link mode as option to CLI**
Hopefully fixes the issue related to [this](https://aqoraquantum.slack.com/archives/C06DPTGL2GP/p1724662504116159?thread_ts=1721233886.412749&cid=C06DPTGL2GP)
=> feat: add dep link mode

src/print.rs
https://aqora.io/competitions/classiq_qinnovision/discussions/AFRvcGljAZMNDTUMfOGNajOoaVauBA/test-error
The issue was originating from trying to access `__name__` on print, so the fix is just to direct all attribute related functions to the underlying overriden function
=> fix: add attr magic functions to overriden python builtins

Cargo.lock, Cargo.toml, src/commands/global_args.rs, src/commands/lab.rs, src/commands/login.rs, src/commands/template.rs, src/commands/upload.rs, src/dirs.rs, src/graphql/accept_competition_rules.graphql, src/graphql/get_viewer_enabled_entities.graphql, src/graphql/join_competition.graphql, src/graphql/latest_submission_version.graphql, src/graphql/schema.graphql, src/progress_bar.rs
- **feat: accept rules with cli**
Needs on #108
=> prompt to accept rules

pyproject.toml
related to : https://github.com/PyO3/maturin/pull/2417
=> chore: fix maturin 1.8.0 build issue

.github/workflows/cd.yaml
based on : https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md
=> fix(ci): upload artifact

src/commands/login.rs, src/credentials.rs, src/graphql/oauth2_refresh.graphql, src/graphql/schema.graphql, src/graphql_client.rs
Requires https://github.com/aqora-io/platform/pull/643 to be merged first
Also adds some helpful debugging to graphql requests
=> fix: add client_secret to oauth refresh

Cargo.lock, Cargo.toml, schema.graphql, src/commands/install.rs, src/commands/upload.rs, src/graphql/get_competition_use_case.graphql, src/graphql/update_submission.graphql, src/graphql/update_use_case.graphql, src/graphql_client.rs, src/id.rs
- **feat: competition stages**
- **fix: use project name from backend**
=> feat leaderboard stage
